#!/usr/bin/env bash

if [[ $# -ne 2 ]]; then
    echo "hgcal-sim-proc [study name] [config dir]"
    exit 0
fi

EXPERIMENT_NAME=$1
CONFIG_DIR=$2

source $CONFIG_DIR/config.sh

intrp_recv=0

# trap process signals
handle_intrp () {
    echo
    if [[ $intrp_recv -eq 0 ]]; then
        echo "shutting down simulation process" >> $CONFIG_DIR/simulation_log.log
        exit 0
    fi
}
trap handle_intrp 2

DCKR_BASE_ARGS="--rm -v $DATA_DIR:/work \
    -v $SCRIPTDIR:/scripts \
    $DCKR_IMG $SIM_RUN_SCRIPT \
    -p $PARTICLE -e $ENERGY -n $NEVENTS -b $EXPERIMENT_NAME"

while true
do
    # read semaphore
    sem=`cat $CONFIG_DIR/semaphore`
    # if, sim launch proc
    if [[ $sem -eq "SIM" ]]; then
        DCKR_ARGS="${DCKR_BASE_ARGS} -s $SEED"
        echo "docker run ${DCKR_ARGS}" >> $CONFIG_DIR/simulation_log.log
        echo "TRAIN" > $CONFIG_DIR/semaphore 
    fi
    sleep 15
done
