#!/usr/bin/env bash

SCRIPTDIR=$(dirname $BASH_SOURCE)

EXPERIMENT_NAME="hgcal1"
CONFIG_DIR=".$EXPERIMENT_NAME"
BATCH_SIZE=60

TRAINCMD=hgcal-train-proc
SIMCMD=hgcal-sim-proc

# data dir
DATA_DIR=/data/me/calox/${EXPERIMENT_NAME}

# simulation configuration
SIM_RUN_SCRIPT=run_sim.sh
DCKR_IMG=calox-hgcal
PARTICLE="pi-"
ENERGY="500 GeV"
NEVENTS=$BATCH_SIZE

# training configuration
MODEL_PATH=$CONFIG_DIR/model.pckl
STANDARDIZER_PATH=$CONFIG_DIR/standardizer.npz

SIMPID=NONE
TRAINPID=NONE

hndl_sig () {
    echo
    echo "Interruption signal recieved - passing to sub-processes."
# kill simulation proc
    if [[ $SIMPID != NONE ]]; then
        kill $SIMPID
    fi
# kill training proc
    if [[ $TRAINPID != NONE ]]; then
        kill $TRAINPID
    fi

    echo "Shutting down"
    exit 0
}

trap hndl_sig 2

# initialize the study
if [[ ! -d $CONFIG_DIR ]]; then
    echo "Intializing the study - $CONFIG_DIR"
    mkdir -p $CONFIG_DIR
    if [[ $? -ne 0 ]]; then
        echo "CANNOT CREATE CONFIG DIR!!"
        exit 1
    fi

    if [[ ! -d $DATA_DIR ]]; then
        mkdir -p $DATA_DIR
        if [[ $? -ne 0 ]]; then
            echo "CANNOT CREATE DATA DIR!!"
            return 1
        fi
    fi

    echo "EXPERIMENT_NAME=$EXPERIMENT_NAME" > $CONFIG_DIR/config.sh
    echo "SCRIPTDIR=$SCRIPTDIR" >> $CONFIG_DIR/config.sh
    echo "BATCH_SIZE=$BATCH_SIZE" >> $CONFIG_DIR/config.sh
    echo "DATA_DIR=$DATA_DIR" >> $CONFIG_DIR/config.sh
    echo "SIM_RUN_SCRIPT=$SIM_RUN_SCRIPT" >> $CONFIG_DIR/config.sh
    echo "DCKR_IMG=$DCKR_IMG" >> $CONFIG_DIR/config.sh
    echo "PARTICLE=\"$PARTICLE\"" >> $CONFIG_DIR/config.sh
    echo "ENERGY=\"$ENERGY\"" >> $CONFIG_DIR/config.sh
    echo "NEVENTS=$NEVENTS" >> $CONFIG_DIR/config.sh
    echo "MODEL_PATH=$MODEL_PATH" >> $CONFIG_DIR/config.sh
    echo "STANDARDIZER_PATH=$STANDARDIZER_PATH" >> $CONFIG_DIR/config.sh

    $SCRIPTDIR/initialize_study.sh $EXPERIMENT_NAME $BATCH_SIZE

    echo "INITIALIZE_MODEL=1" >> $CONFIG_DIR/mod_state
    echo "STANDARDIZE_DATA=1" >> $CONFIG_DIR/data_state

    # write the initial state
    echo "1 0" > $CONFIG_DIR/state
    echo "SIM" > $CONFIG_DIR/semaphore
else 
    echo "Study already initialized, recovering check-point."
fi


# kick off training process
#bash $SCRIPTDIR/$TRAINCMD $EXPERIMENT_NAME $CONFIG_DIR &
#TRAINPID=$!

# kick off simulation process
echo "Kicking off simulation process"
bash $SCRIPTDIR/$SIMCMD $EXPERIMENT_NAME $CONFIG_DIR &
SIMPID=$!


wait
